modLoader="javafml"
loaderVersion="[57, )"
license="All Rights Reserved"

[[mods]]
modId="artillery"
version="${mod_version}"
displayName="Artillery Mod"
author="YourName"
description='''Artillery system with ballistic solver and recon camera.'''

[[dependencies.artillery]]
modId="forge"
mandatory=true
versionRange="[57,)"
ordering="NONE"
side="BOTH"

[[dependencies.artillery]]
modId="minecraft"
mandatory=true
versionRange="[1.21.7]"
ordering="NONE"
side="BOTH"
